# Generated by Django 4.2.12 on 2024-07-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=256, null=True)),
                ('wholesale_discount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
