# Generated by Django 4.2.12 on 2024-05-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_email',
            field=models.CharField(default='null', max_length=256),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_number',
            field=models.IntegerField(default=0000000000, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='wholesale_discount',
            field=models.IntegerField(default=0),
        ),
    ]
