# Generated by Django 4.2.12 on 2024-05-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_contact_email_supplier_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_email',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='wholesale_discount',
            field=models.IntegerField(null=True),
        ),
    ]
