# Generated by Django 4.2.12 on 2024-05-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_alter_supplier_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
