# Generated by Django 4.2.12 on 2024-07-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('picture_url', models.URLField(blank=True)),
                ('sku', models.CharField(max_length=256)),
            ],
        ),
    ]
