# Generated by Django 4.2.12 on 2024-07-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mead', '0002_alter_meaditem_retail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaditem',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
