# Generated by Django 4.2.12 on 2024-05-22 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_category', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=256)),
                ('sku', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('supply_price', models.IntegerField()),
                ('retail_price', models.IntegerField()),
                ('brand_name', models.CharField(max_length=256)),
                ('active', models.BooleanField()),
                ('track_inventory', models.IntegerField()),
                ('outlet_tax_main_outlet', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('is_premium', models.BooleanField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ties', to='accessories.accessory')),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ties', to='accessories.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='BowTie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=256)),
                ('sku', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('supply_price', models.IntegerField()),
                ('retail_price', models.IntegerField()),
                ('brand_name', models.CharField(max_length=256)),
                ('active', models.BooleanField()),
                ('track_inventory', models.IntegerField()),
                ('outlet_tax_main_outlet', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('is_premium', models.BooleanField()),
                ('is_pretied', models.BooleanField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowties', to='accessories.accessory')),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowties', to='accessories.supplier')),
            ],
        ),
    ]
