# Generated by Django 4.2.12 on 2024-07-08 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=256)),
                ('sku', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('color_id', models.IntegerField(null=True)),
                ('color_name', models.CharField(max_length=256, null=True)),
                ('supply_price', models.IntegerField()),
                ('retail_price', models.IntegerField()),
                ('brand_name', models.CharField(max_length=256)),
                ('current_inventory', models.IntegerField(default=0)),
                ('number_sold', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('is_premium', models.BooleanField()),
                ('picture_url', models.URLField(blank=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ties', to='accessories.accessory')),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ties', to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PocketSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=256)),
                ('sku', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('supply_price', models.IntegerField()),
                ('retail_price', models.IntegerField()),
                ('brand_name', models.CharField(max_length=256)),
                ('current_inventory', models.IntegerField(default=0)),
                ('number_sold', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('is_premium', models.BooleanField()),
                ('picture_url', models.URLField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('outlet_tax_main_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocketsquares', to='suppliers.taxzone')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocketsquares', to='accessories.accessory')),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocketsquares', to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='BowTie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=256)),
                ('sku', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('supply_price', models.IntegerField()),
                ('retail_price', models.IntegerField()),
                ('brand_name', models.CharField(max_length=256)),
                ('current_inventory', models.IntegerField(default=0)),
                ('number_sold', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('is_premium', models.BooleanField()),
                ('is_pretied', models.BooleanField()),
                ('picture_url', models.URLField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('outlet_tax_main_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowties', to='suppliers.taxzone')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowties', to='accessories.accessory')),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowties', to='suppliers.supplier')),
            ],
        ),
    ]
