# Generated by Django 4.2.12 on 2024-07-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tie',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
