# Generated by Django 4.2.12 on 2024-05-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_rename_track_inventory_bowtie_number_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bowtie',
            name='active',
        ),
        migrations.RemoveField(
            model_name='tie',
            name='active',
        ),
        migrations.AddField(
            model_name='bowtie',
            name='current_inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tie',
            name='current_inventory',
            field=models.IntegerField(default=0),
        ),
    ]
