# Generated by Django 4.2.12 on 2024-05-22 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('accessories', '0003_remove_bowtie_active_remove_tie_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowtie',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowties', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ties', to='suppliers.supplier'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
