# Generated by Django 4.2.12 on 2024-05-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0004_alter_bowtie_supplier_name_alter_tie_supplier_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='accessory_category',
        ),
    ]
