# Generated by Django 4.2.12 on 2024-05-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0006_bowtie_picture_url_tie_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowtie',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tie',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
