# Generated by Django 4.2.12 on 2024-05-23 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_alter_supplier_contact_email_and_more'),
        ('accessories', '0007_bowtie_tags_tie_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocketSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=256)),
                ('sku', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('supply_price', models.IntegerField()),
                ('retail_price', models.IntegerField()),
                ('brand_name', models.CharField(max_length=256)),
                ('current_inventory', models.IntegerField(default=0)),
                ('number_sold', models.IntegerField()),
                ('outlet_tax_main_outlet', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('is_premium', models.BooleanField()),
                ('picture_url', models.URLField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocketsquares', to='accessories.accessory')),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocketsquares', to='suppliers.supplier')),
            ],
        ),
    ]
