# Generated by Django 4.2.12 on 2024-05-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_taxzone'),
        ('accessories', '0008_pocketsquare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowtie',
            name='outlet_tax_main_outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowties', to='suppliers.taxzone'),
        ),
        migrations.AlterField(
            model_name='pocketsquare',
            name='outlet_tax_main_outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocketsquares', to='suppliers.taxzone'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='outlet_tax_main_outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ties', to='suppliers.taxzone'),
        ),
    ]
