# Generated by Django 4.2.12 on 2024-06-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0010_remove_tie_outlet_tax_main_outlet_remove_tie_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tie',
            name='color_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tie',
            name='color_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
